In [ ]:
import numpy
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Flatten

from tensorflow.keras.layers import Conv2D
from keras.optimizers import Adam
from keras.utils import np_utils

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
x_train = x_train.reshape(60000, 28, 28, 1).astype('float32')
x_test = x_test.reshape(10000, 28, 28, 1).astype('float32')

In [ ]:
number_of_classes = 10
y_train = np_utils.to_categorical(y_train, number_of_classes)
y_test = np_utils.to_categorical(y_test, number_of_classes)

In [ ]:
model = Sequential()
model.add(Conv2D(64, (3, 3), input_shape = (28, 28, 1), activation = 'relu'))
model.add(Conv2D(32, (3, 3),activation = 'relu'))
model.add(Flatten())
model.add(Dense(number_of_classes, activation = 'softmax'))

In [ ]:
model.compile(loss = 'categorical_crossentropy', optimizer = "Adam", metrics = ['accuracy'])

In [ ]:
model.fit(x_train, y_train, validation_data = (x_test, y_test), epochs = 5, batch_size = 32)

Epoch 1/5
1875/1875 [==============================] - 190s 101ms/step - loss: 0.2325 - accuracy: 0.9495 - val_loss: 0.0959 - val_accuracy: 0.9711
Epoch 2/5
1875/1875 [==============================] - 190s 101ms/step - loss: 0.0709 - accuracy: 0.9789 - val_loss: 0.0848 - val_accuracy: 0.9761
Epoch 3/5
1875/1875 [==============================] - 187s 100ms/step - loss: 0.0500 - accuracy: 0.9836 - val_loss: 0.1037 - val_accuracy: 0.9765
Epoch 4/5
1875/1875 [==============================] - 184s 98ms/step - loss: 0.0368 - accuracy: 0.9887 - val_loss: 0.1116 - val_accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 184s 98ms/step - loss: 0.0309 - accuracy: 0.9908 - val_loss: 0.1320 - val_accuracy: 0.9777


In [ ]:
metrics = model.evaluate(x_test, y_test, verbose = 0)
print("Metrics(Test loss & Test Accuracy):")
print(metrics)

Metrics(Test loss & Test Accuracy):
[0.11623921245336533, 0.9761000275611877]


In [ ]:
prediction = model.predict(x_test[:4])
print(prediction)

1/1 [==============================] - 0s 97ms/step
[[1.2437441e-10 6.3942137e-19 5.5431929e-07 1.6169508e-08 2.1894654e-13
  2.3941803e-14 2.8406087e-20 9.9999928e-01 4.7412825e-12 8.0360500e-08]
 [6.6959659e-13 2.0964447e-07 9.9999976e-01 1.0089480e-09 3.8388599e-17
  2.1256348e-14 2.0385054e-08 1.1833877e-21 2.1424102e-09 7.4830155e-19]
 [2.9385890e-07 9.9972326e-01 5.5384539e-06 9.4967179e-14 2.6868528e-04
  2.2555859e-07 4.3053661e-10 1.2761404e-09 2.0751997e-06 1.6646802e-09]
 [9.9999595e-01 3.6993414e-15 2.1205717e-06 8.6421443e-14 1.9172881e-10
  7.5451749e-11 5.5626094e-07 1.5134912e-11 9.4758895e-11 1.3759874e-06]]


In [ ]:
import numpy as np
print(np.argmax(prediction, axis=1))
print(y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
model.save('models/mnistCNN.h5')

In [ ]:
from google.colab import files
files.download("models/mnistCNN.h5")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>